apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: soliditydev-pl-tls
spec:
  secretName: soliditydev-pl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: soliditydev.pl
  dnsNames:
    - soliditydev.pl
    - www.soliditydev.pl
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - soliditydev.pl
          - www.soliditydev.pl
